ServerName: 'Server'
CustomWelcome: true
CustomGoodbye: true
NewPlayerWelcome: true
EnableEChestCommand: true
EnableDieCommand: true
EnableKits: true
AxeKitItems:
  - 'iron_axe 1'
  - 'cooked_beef 16'
  - 'golden_apple 1'
  - 'shield 1'
  - 'iron_helmet 1'
  - 'iron_chestplate 1'
  - 'iron_leggings 1'
  - 'iron_boots 1'
SwordKitItems:
  - 'iron_sword 1'
  - 'golden_axe 1'
  - 'cooked_beef 16'
  - 'golden_apple 1'
  - 'shield 1'
  - 'diamond_helmet 1'
  - 'diamond_chestplate 1'
  - 'diamond_leggings 1'
  - 'diamond_boots 1'


