ServerName: 'Server'
CustomWelcome: true
CustomGoodbye: true
NewPlayerWelcome: true
EnableEChestCommand: true
EnableDieCommand: true
EnableKits: true
OneKitPerLife: true
RemoveKitItemsOnDeath: true
PreventPlayerFromDroppingKitItems: true
PreventPlayerFromStoringKitItemsInChests: true
AxeKitItems:
  - 'iron_axe 1'
  - 'cooked_beef 16'
  - 'golden_apple 1'
  - 'shield 1'
  - 'iron_helmet 1'
  - 'iron_chestplate 1'
  - 'iron_leggings 1'
  - 'iron_boots 1'
SwordKitItems:
  - 'iron_sword 1'
  - 'golden_axe 1 unbreaking-3'
  - 'cooked_beef 16'
  - 'golden_apple 1'
  - 'shield 1'
  - 'diamond_helmet 1'
  - 'diamond_chestplate 1'
  - 'diamond_leggings 1'
  - 'diamond_boots 1'
BowKitItems:
  - 'bow 1 power-2 infinity-1 unbreaking-1'
  - 'golden_axe 1 unbreaking-3'
  - 'stone_sword 1'
  - 'cooked_beef 16'
  - 'golden_apple 1'
  - 'shield 1'
  - 'leather_helmet 1'
  - 'leather_chestplate 1'
  - 'leather_leggings 1'
  - 'leather_boots 1 feather_falling-4'
  - 'arrow 1'
CrossbowKitItems:
  - 'crossbow 1 quick_charge-1'
  - 'golden_axe 1 unbreaking-3'
  - 'stone_sword 1'
  - 'cooked_beef 16'
  - 'golden_apple 1'
  - 'shield 1'
  - 'golden_helmet 1 unbreaking-3'
  - 'golden_chestplate 1 unbreaking-3'
  - 'golden_leggings 1 unbreaking-3'
  - 'golden_boots 1 unbreaking-3 feather_falling-2'
  - 'arrow 64'
TankKitItems:
  - 'stone_sword 1'
  - 'stone_axe 1'
  - 'golden_apple 1'
  - 'netherite_helmet 1'
  - 'netherite_chestplate 1'
  - 'netherite_leggings 1'
  - 'netherite_boots 1'
